eCommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('xystusVal_admin/defender/', include('defender.urls')),
    path('xystusVal_admin/', admin.site.urls),
    path('', include('store.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('categories/', views.categories, name='categories'),
    path('cart/', views.cart, name='cart'),
    path('shop/', views.shop, name='shop'),
    path('order/', views.order, name='order'),
    path('contact/', views.contact, name='contact'),
    path('checkout/', views.checkout, name='checkout'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('update_item/', views.update_item, name='update_item'),
    path('process_order/', views.processOrder, name='process_order'),
    path('product_detail/<str:product_id>/', views.productDetail, name='product_detail'),
    path('product_type/<str:pk>/', views.product_type_detail, name='product_type_detail'),
    path('product', views.product, name='product'),
    path('addProduct', views.addProduct, name='addProduct'),
    path('updateProduct/<str:product_id>/', views.updateProduct, name='updateProduct'),
    path('addCategory', views.addCategory, name='addCategory'),
    path('addProductType', views.addProductType, name='addProductType'),

]

store/models.py
from django.conf import settings
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.loader import render_to_string


# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class ProductType(models.Model):
    name = models.CharField(max_length=200, null=True)
    image = models.ImageField(blank=True, null=True)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200, null=True)
    image = models.ImageField(blank=True, null=True)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    product_type = models.ForeignKey(ProductType, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(blank=True, max_length=5000, null=True)
    original_price = models.DecimalField(max_digits=20, decimal_places=2)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    shipping = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(blank=True, null=True)
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} selling for {self.price}'

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


@receiver(post_save, sender=Product)
def send_product_added_email(sender, instance, created, **kwargs):
    if created:
        subject = 'New Product Added!'
        message = f'Dear customer,\nWe are excited to inform you that a new product "{instance.name}" has been added to our collection.\n' \
                  f'Visit our website to explore the latest additions!\nThank you for choosing us.\n\n' \
                  f'You can check out the new product here: https://xystusshop.pythonanywhere.com'

        # Fetch the email addresses of all customers
        recipient_list = list(Customer.objects.values_list('email', flat=True))

        try:
            # Try sending the email
            send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, recipient_list, fail_silently=False)
        except Exception as e:
            # Log or print the exception for debugging purposes
            print(f"Email sending failed: {e}")

    # Save the new product even if the email sending fails
    # instance.save()


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f'orderID = {str(self.id)}, Customer = {self.customer.name}'

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitem = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitem])
        return total

    @property
    def get_cart_items(self):
        orderitem = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitem])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    @property
    def get_total(self):
        total = (self.product.price * self.quantity) + self.product.shipping
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    address = models.CharField(max_length=200, null=True)
    town = models.CharField(max_length=200, null=True)
    lga = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.address} for {self.customer.name}'

store/views.py
import random
from django.contrib import messages
from django.http import JsonResponse
import json
import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from .models import *
from .forms import *
from .utils import cookieCart, cartData, guestOrder
from .filters import *
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import user_passes_test


# Create your views here.
def is_admin(user):
    return user.is_authenticated and user.is_staff


def index(request):
    data = cartData(request)
    cartItems = data['cartItems']

    product_types = ProductType.objects.all()[:6]

    products = Product.objects.all()

    # Shuffle the products
    products_list = list(products)
    random.shuffle(products_list)

    product_page = Paginator(products_list, 16)
    page_number = request.GET.get('page')

    try:
        product_page = product_page.get_page(page_number)
    except PageNotAnInteger:
        product_page = product_page.page(1)
    except EmptyPage:
        product_page = product_page.page(product_page.num_pages)

    cheapest = Product.objects.order_by('price')[:10]
    latest_products = Product.objects.all().order_by('-added_at')[:12]

    context = {
        'product_page': product_page,  # Include paginated products
        'product_types': product_types,
        'cheapest': cheapest,
        'latest_products': latest_products,
        'cartItems': cartItems,
    }
    return render(request, 'store/index.html', context)


def product_type_detail(request, pk):
    data = cartData(request)
    cartItems = data['cartItems']

    product_type = get_object_or_404(ProductType, pk=pk)
    products = Product.objects.filter(product_type=product_type)

    context = {
        'product_type': product_type,
        'products': products,
        'cartItems': cartItems,
    }
    return render(request, 'store/product_type_detail.html', context)


def categories(request):
    data = cartData(request)
    cartItems = data['cartItems']

    products = Product.objects.all()
    my_filter = ProductFilter(request.GET, queryset=products)
    products = my_filter.qs

    # Convert the queryset to a list and shuffle it
    products_list = list(products)
    random.shuffle(products_list)

    context = {
        'cartItems': cartItems,
        'products': products_list,  # Use the shuffled list
        'my_filter': my_filter,
    }
    return render(request, 'store/categories.html', context)


def cart(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {
        'items': items,
        'order': order,
        'cartItems': cartItems,
    }
    return render(request, 'store/cart.html', context)


def checkout(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    paystack_public_key = settings.PAYSTACK_PUBLIC_KEY
    paystack_secret_key = settings.PAYSTACK_SECRET_KEY

    context = {
        'items': items,
        'order': order,
        'cartItems': cartItems,
        'paystack_public_key': paystack_public_key,
        'paystack_secret_key': paystack_secret_key,
    }
    return render(request, 'store/checkout.html', context)


def update_item(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('ProductId:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)


def clear_cart(request):
    customer = request.user.customer
    cart_items = Order.objects.get(customer=customer, complete=False)
    cart_items.orderitem_set.all().delete()

    return JsonResponse('Cart was cleared', safe=False)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    try:
        data = json.loads(request.body)
    except json.JSONDecodeError as e:
        return JsonResponse({'error': f'Error decoding JSON: {e}'}, status=400)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == float(order.get_cart_total):
        order.complete = True
    order.save()

    if order.shipping:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            phone=data['shipping']['phone'],
            email=data['shipping']['email'],
            address=data['shipping']['address'],
            town=data['shipping']['town'],
            lga=data['shipping']['lga'],
            state=data['shipping']['state'],
        )

    return JsonResponse('Payment Complete', safe=False)


def shop(request):
    query = request.GET.get('query', '')
    results = []

    if query:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data.get('query')
            results = Product.objects.filter(name__icontains=query) | Product.objects.filter(
                description__icontains=query)
    else:
        form = SearchForm()

    data = cartData(request)
    cartItems = data['cartItems']

    products = Product.objects.all()
    # Convert the queryset to a list and shuffle it
    products_list = list(products)
    random.shuffle(products_list)

    context = {
        'cartItems': cartItems,
        'products': products_list,
        'results': results,
        'form': form,
    }
    return render(request, 'store/shop.html', context)


def productDetail(request, product_id):
    product_detail = Product.objects.get(id=product_id)
    quick_products = Product.objects.all()[:8]

    explore_products = Product.objects.filter(product_type=product_detail.product_type).exclude(id=product_detail.id)[
                       :12]
    # Convert the queryset to a list and shuffle it
    products_list = list(explore_products)
    random.shuffle(products_list)

    data = cartData(request)
    cartItems = data['cartItems']
    context = {
        'cartItems': cartItems,
        'product_detail': product_detail,
        'quick_products': quick_products,
        'explore_products': products_list,
    }
    return render(request, 'store/product_detail.html', context)


@user_passes_test(is_admin)
def order(request):
    data = cartData(request)
    cartItems = data['cartItems']

    orders = Order.objects.all().order_by('-date_ordered')

    context = {
        'cartItems': cartItems,
        'orders': orders,
    }
    return render(request, 'store/orders.html', context)


def contact(request):
    data = cartData(request)
    cartItems = data['cartItems']

    context = {
        'cartItems': cartItems,
    }
    return render(request, 'store/contact.html', context)


@user_passes_test(is_admin)
def product(request):
    data = cartData(request)
    cartItems = data['cartItems']

    products = Product.objects.all()
    my_filter = ProductPage(request.GET, queryset=products)
    products = my_filter.qs

    context = {
        'cartItems': cartItems,
        'products': products,
        'my_filter': my_filter,
    }
    return render(request, 'store/product.html', context)


@user_passes_test(is_admin)
def addProduct(request):
    form = AddProductForm()
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product added successfully.')
            return redirect('product')  # Update 'home' to your home page URL name
        else:
            messages.error(request, 'Form submission failed. Please check the data.')

    context = {
        'form': form,
    }
    return render(request, 'store/add_product.html', context)


@user_passes_test(is_admin)
def updateProduct(request, product_id):
    products = get_object_or_404(Product, id=product_id)
    form = UpdateProductForm(instance=products)

    if request.method == "POST":
        form = UpdateProductForm(request.POST, request.FILES, instance=products)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product updated successfully.')
            return redirect('product')
        else:
            messages.error(request, 'Form submission failed. Please check the data.')

    context = {
        'form': form,
        'products': products,
    }
    return render(request, 'store/update_product.html', context)


@user_passes_test(is_admin)
def addCategory(request):
    form = CategoryForm
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'New Category Added successfully.')
            return redirect('product')
        else:
            messages.error(request, 'Form submission failed. Please check the data.')

    category = Category.objects.all()

    context = {
        'form': form,
        'category': category,
    }
    return render(request, 'store/add_category.html', context)


@user_passes_test(is_admin)
def addProductType(request):
    form = ProductTypeForm
    if request.method == 'POST':
        form = ProductTypeForm(request.POST, request.FILES)

store/templates/store/add_category.html
<!doctype html>
{% load static %}
{% load custom_filters %}
<html class="no-js" lang="zxx">

<!--HTML Head Links-->
{% include 'store/head.html' %}
<body>

<!--Preloader-->
{% include 'store/preloader.html' %}


<!--Nav Bar-->
{% include 'store/navbar.html' %}

<main>

<div style="margin-top: 5em;">

</div>


<div class="latest-items section-padding fix text-center" style="padding-top: 20px; padding-bottom: 150px;">



    <section>
        <div class="container mb-5">
            <h3>Add Category</h3>

            {% if messages %}
				{% for message in messages %}
					<div class="alert alert-primary alert-dismissible fade show" role="alert">
						{{ message }}
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
				{% endfor %}
			{% endif %}

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="body">
                    {{ form.as_p }}

                    <div class="row text-center">
                        <div class="col-sm-12 col-md-12 mt-5">
                            <button type="submit" style="border-radius: 0.5em;" class="btn btn-primary">Submit</button>
                            <a href="{% url 'product' %}" style="border-radius: 0.5em;" class="btn btn-primary">Back</a>
                        </div>
                    </div>
                </div>
            </form>

            <table class="table">
				<thead>
					<tr style="font-size: 80%; font-weight: bold;">
						<th scope="col">Image</th>
						<th scope="col">Name</th>
					</tr>
				</thead>
				<tbody style="font-size: 11px; font-weight: bold;">
					{% for category in category %}
					<tr>
						<td><img src="{{ category.imageURL }}" alt="Product Image" style="max-width: 50px; max-height: 50px;"></td>
						<td>{{ category.name }}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>

        </div>
    </section>

</div>


</main>

<!--Footer-->
{% include 'store/footer.html' %}

<button id="myBtn" title="Go to top">Top</button>


<!--Bottom Scripts-->
<script nonce="{{ request.csp_nonce }}">
    // Automatically close alert messages after 4 seconds
    window.setTimeout(function() {
        $(".alert").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove();
        });
    }, 4000);
</script>
{% include 'store/bottom_scripts.html' %}
</body>

</html>

store/templates/store/bottom_scripts.html
{% load static %}
<script src="{% static 'assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/js/slick.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.slicknav.min.js' %}"></script>

<script src="{% static 'assets/js/wow.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.magnific-popup.js' %}"></script>
<script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'assets/js/waypoints.min.js' %}"></script>
<script src="{% static 'assets/js/price_rangs.js' %}"></script>

<script src="{% static 'assets/js/contact.js' %}"></script>
<script src="{% static 'assets/js/jquery.form.js' %}"></script>
<script src="{% static 'assets/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'assets/js/mail-script.js' %}"></script>
<script src="{% static 'assets/js/jquery.ajaxchimp.min.js' %}"></script>

<script src="{% static 'assets/js/plugins.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
<script src="{% static 'assets/js/cart.js' %}"></script>
<script src="{% static 'assets/js/back_to_top.js' %}"></script>


<script nonce="{{ request.csp_nonce }}">
    window.onscroll = function() {myFunction()};

    var header = document.querySelector(".fixed-top");
    var sticky = header.offsetTop;

    function myFunction() {
        if (window.pageYOffset > sticky) {
            header.classList.add("fixed");
        } else {
            header.classList.remove("fixed");
        }
    }
</script>


<script nonce="{{ request.csp_nonce }}">
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>

<script nonce="{{ request.csp_nonce }}">
	var topBtn = document.getElementById('myBtn');
	topBtn.addEventListener('click', function(e) {
        topFunction();
    });
</script>

store/templates/store/cart.html
<!doctype html>
{% load static %}
{% load custom_filters %}
<html class="no-js" lang="zxx">

<!--HTML Head Links-->
{% include 'store/head.html' %}
<body>

<!--Preloader-->
{% include 'store/preloader.html' %}

<!--Nav Bar-->
{% include 'store/navbar.html' %}

<main>

<div class="hero-area section-bg2 mb-5">
<div class="container">
<div class="row">
<div class="col-xl-12">
<div class="slider-area">
<div class="slider-height2 slider-bg4 d-flex align-items-center justify-content-center">
<div class="hero-caption hero-caption2">
<nav aria-label="breadcrumb">
<ol class="breadcrumb justify-content-center">
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="#">Cart</a></li>
</ol>
</nav>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

<div class="container mb-5">

    <div class="row">
    <div class="col-md-12">
        <div class="box-element">

				<a  class="btn btn-primary" style="border-radius: 0.5em;" href="{% url 'shop' %}">&#x2190; Continue Shopping</a>

				<hr style="border-color: black; margin-top: 1%;">
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
						<th><h5>Total:<strong> ₦{{order.get_cart_total|format_price}}</strong></h5></th>
						<th>
							{% if not order.get_cart_items == 0  %}
							<a  style="float:right; margin-top: -3%; margin-bottom: 1em; border-radius: 0.5em;" class="btn btn-primary" href="{% url 'checkout' %}">Checkout</a>
							<a  style="float:right; margin-top: -3%; margin-right: 1em; border-radius: 0.5em;" id="clearCart" class="btn btn-primary" href="#">Clear</a>
							{% endif %}
						</th>
					</tr>
				</table>

        </div>

        <br>
        <div class="box-element text-center" style="box-sizing: border-box;">
			<table class="table">
				<thead>
					<tr style="font-size: 80%; font-weight: bold;">
						<th scope="col">Image</th>
						<th scope="col">Item</th>
						<th scope="col">Price</th>
						<th scope="col">Shipping</th>
						<th scope="col">Quantity</th>
						<th scope="col">Total</th>
					</tr>
				</thead>
				<tbody style="font-size: 11px; font-weight: bold;">
					{% for item in items %}
					<tr>
						<td><img src="{{ item.product.imageURL }}" alt="Product Image" style="max-width: 50px; max-height: 50px;"></td>
						<td>{{ item.product.name }}</td>
						<td>₦{{ item.product.price|format_price }}</td>
						<td>₦{{ item.product.shipping|format_price }}</td>
						<td>
							<p class="quantity" style="font-size: 13px; font-weight: bold;">{{ item.quantity }}</p>
							<div class="quantity">
								<img data-product="{{ item.product.id }}" data-action="add" class="chg-quantity update-cart" src="{% static 'assets/img/arrow-up.png' %}">
								<img data-product="{{ item.product.id }}" data-action="remove" class="chg-quantity update-cart" src="{% static 'assets/img/arrow-down.png' %}">
							</div>
						</td>
						<td>₦{{ item.get_total|format_price }}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>

        </div>
    </div>
</div>

</div>




</main>

<!--Footer-->
{% include 'store/footer.html' %}

<button id="myBtn" title="Go to top">Top</button>


<!--Bottom Scripts-->

{% include 'store/bottom_scripts.html' %}
<script nonce="{{ request.csp_nonce }}">
    var clear_cart = document.getElementById('clearCart');
	if (clear_cart) {
		clear_cart.addEventListener('click', function(e) {
			clearCart();
		});
	}
</script>
</body>

</html>

store/templates/store/footer.html
{% load static %}
<footer style="background-color: black;">
<div class="footer-area footer-padding">

<section class="subscribe-area">
<div class="container">
<div class="row justify-content-between subscribe-padding">
<div class="col-xxl-3 col-xl-3 col-lg-4">

    <div class="footer-logo mb-35">
        <a href="{% url 'index' %}"><img style="height: 4.5em;" src="{% static 'assets/img/logo/footer_logo.png' %}" alt=""></a>
    </div>

</div>

<div class="col-xxl-5 col-xl-6 col-lg-7 col-md-9">
<div class="subscribe-caption">
<form action="#">
<input type="text" name="email_sub" placeholder="Enter your email">
<button class="subscribe-btn">Subscribe</button>
</form>
</div>
    <div class="subscribe-caption" style="margin-top: 15px;">
        <h3>Subscribe Newsletter</h3>
        <p>Subscribe newsletter to get updates on our newest products.</p>
    </div>
</div>
<div class="col-xxl-2 col-xl-2 col-lg-4">

<div class="footer-social">
<a href="https://bit.ly/sai4ull"><i class="fab fa-facebook"></i></a>
<a href="#"><i class="fab fa-instagram"></i></a>
<a href="#"><i class="fab fa-youtube"></i></a>

</div>
</div>
</div>
</div>
</section>

</div>

<div class="footer-bottom-area">
<div class="container">

<div class="row">
<div class="col-xl-12 ">
<div class="footer-copy-right text-center">
<p>Copyright &copy; 2023  ::  All rights reserved </p>
</div>
</div>
</div>

</div>
</div>
</footer>

store/templates/store/orders.html
<!doctype html>
{% load static %}
{% load custom_filters %}
<html class="no-js" lang="zxx">

<!--HTML Head Links-->
{% include 'store/head.html' %}
<body>

<!--Preloader-->
{% include 'store/preloader.html' %}

<!--Nav Bar-->
{% include 'store/navbar.html' %}

<main>

<div class="hero-area section-bg2 mb-5">
<div class="container">
<div class="row">
<div class="col-xl-12">
<div class="slider-area">
<div class="slider-height2 slider-bg4 d-flex align-items-center justify-content-center">
<div class="hero-caption hero-caption2">
<h2>Orders</h2>
<nav aria-label="breadcrumb">
<ol class="breadcrumb justify-content-center">
<li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="#">Orders</a></li>
</ol>
</nav>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

<div class="container mb-5">

<div class="row">
    <div class="col-md-12">
        <div class="box-element text-center" style="padding: 2em;">


            <div class="row clearfix">
                {% for order in orders %}
                <div class="col-md-4" style="margin-bottom: 1.5em;">
                    <div class="card box-element" style="padding: 2em;">
                        <div class="body">
                            <!-- orders.html -->
                            <h2>Order {{ order.id }}</h2>
                            <p>Customer: {{ order.customer.name }}</p>
                            <p>Complete?? {{ order.complete }}</p>

                            <!-- Order Items -->
                            <div class="card box-element" style="margin-bottom: 1.5em;">
                                <h3>Order Items:</h3>

                            <ul>
                                {% for item in order.orderitem_set.all %}
                                    <li><img src="{{ item.product.imageURL }}" alt="Product Image" style="max-width: 50px; max-height: 50px;"></li>
                                    <li style="margin-bottom: 0.8em;">{{ item.product.name }} >> Quantity: {{ item.quantity }} >> Total: ₦{{ item.get_total|format_price }}</li>
                                {% endfor %}
                            </ul>
                            </div>


                            <!-- Shipping Address -->
                            {% for shippingaddress in order.shippingaddress_set.all %}
                                <h3>Shipping Address:</h3>
                                <p>Phone: {{ shippingaddress.phone }}</p>
                                <p>Email: {{ shippingaddress.email }}</p>
                                <p>Address: {{ shippingaddress.address }}, {{ shippingaddress.town }}, {{ shippingaddress.lga }} LGA, {{ shippingaddress.state }} State.</p>
                                <br><br>
                                <strong>Date Ordered: {{ shippingaddress.date_added }}</strong>

                            {% endfor %}

                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>

    </div>
</div>

</div>




</main>

<!--Footer-->
{% include 'store/footer.html' %}

<button id="myBtn" title="Go to top">Top</button>


<!--Bottom Scripts-->
{% include 'store/bottom_scripts.html' %}
</body>

</html>